### ISSUE TITLE
If a configuration is not compiled, the error message isn't clear enough.

### ISSUE THREAD

**Issue by schmidtw** [goschtalt/goschtalt#56]
If you don't pass in the `AutoCompile()` option or call the `Compile()` method, the error message shows:

```
Error: the Compile() function must be called first
```

Which is ok, but it should really reference the 3 supported options goschtalt library provides:

- [ ] `AutoCompile()` option
- [x] `Compile()` method
- [ ] Importing the `typical` package

**Comment by renaz6** [comment]
I had trouble with this last week! 
Making the documentation clearer would be helpful as well. For example, [here](https://github.com/goschtalt/goschtalt/blob/ca716d4e859aec7f9349f129bb854d8d78969cd7/options.go#L325), 

> The enable bool value is optional & assumed to be `true` if omitted.

leads one to think that auto compiling is the default behavior, yet in the same comment section it also states the contradictory statement:

> Default
> AutoCompile is not enabled.

This makes it confusing to know what the intentions are at a glance. 

Perhaps it would be a good idea to mention the `typical` package there as well.

**Comment by schmidtw** [comment]
Thank you for the feedback.  I am thinking that we should change `AutoCompile()` from being the option, to being the default as well.  Only in rare cases would folks not want the compilation to be automatic.

**Comment by schmidtw** [comment]
After more thought, I think the right thing to do is to automatically compile & make a breaking change.  #57 does this and `v0.23.0` includes this new default.
